/** English names for the B1 topics, keyed by topic slug. */
export const TOPIC_EN: Record<string, string> = {
  "datos-personales-y-etapas-de-la-vida": "Personal details and stages of life",
  "rasgos-fisicos": "Physical features",
  "rasgos-de-personalidad": "Personality traits",
  "emociones-y-reacciones": "Emotions and reactions",
  "procesos-mentales": "Mental processes",
  "discusion-y-debate": "Discussion and debate",
  "vivienda-y-alojamiento": "Housing and accommodation",
  "objetos-del-hogar": "Household objects",
  "herramientas-y-bricolaje": "Tools and DIY",
  "ciudad-y-campo": "City and countryside",
  "agricultura-y-ganaderia": "Farming and livestock",
  "vida-laboral": "Working life",
  "finanzas-y-negocios": "Finance and business",
  "exito-y-logro": "Success and achievement",
  "fracaso-y-obstaculos": "Failure and obstacles",
  "vida-civica": "Civic life",
  "cuestiones-sociales": "Social issues",
  "medio-ambiente": "The environment",
  "naturaleza-y-vida-silvestre": "Nature and wildlife",
  "ley-y-orden": "Law and order",
  "guerra-y-conflicto": "War and conflict",
  "historia-y-reinado": "History and monarchy",
  "religion-y-creencias": "Religion and beliefs",
  comportamiento: "Behaviour",
  "educacion-y-academia": "Education and academia",
  "disciplinas-academicas": "Academic subjects",
  "ciencia-e-investigacion": "Science and research",
  "medios-de-comunicacion-y-periodismo": "Media and journalism",
  transporte: "Transport",
  "coches-y-conduccion": "Cars and driving",
  "informatica-y-tecnologia": "Computing and technology",
  "redes-sociales": "Social media",
  deportes: "Sports",
  "cuerpo-humano": "The human body",
  "salud-y-medicina": "Health and medicine",
  "moda-y-vestimenta": "Fashion and clothing",
  "cuidado-personal-e-higiene": "Personal care and hygiene",
  "tratamientos-de-belleza": "Beauty treatments",
  "maquillaje-y-cosmeticos": "Make-up and cosmetics",
  "alimentacion-y-dieta": "Food and diet",
  carne: "Meat",
  "artes-y-entretenimiento": "Arts and entertainment",
  musica: "Music",
  literatura: "Literature",
  "celebraciones-y-fiestas": "Celebrations and parties",
  "juegos-y-juguetes": "Games and toys",
  cantidades: "Quantities",
};

export const topicEn = (slug: string): string => TOPIC_EN[slug] ?? slug;
